# Generated by Django 2.1.11 on 2020-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191118_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=False),
        ),
    ]
