# Generated by Django 2.1.11 on 2020-05-15 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0004_auto_20191218_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='LmtWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_core_hour', models.BigIntegerField(default=0, verbose_name='总核时')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2020, 5, 15, 9, 59, 46, 255518, tzinfo=utc), verbose_name='充值时间')),
                ('admin', models.ForeignKey(db_column='admin_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_id', to=settings.AUTH_USER_MODEL, verbose_name='为其充值的管理员')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
